 
const allcategories = [
    {"category": "Thiết bị ngành giấy", "encategory": "Paper Tester", "urlcategory": "thiet-bi-nganh-giay", "urlencategory": "paper-tester"},
    {"category" :"Bể cách thủy/ Bể điều nhiệt", "encategory": "Water Bath", "urlcategory": "be-cach-thuy-be-dieu-nhiet", "urlencategory": "water-bath"},
    {"category" :"Khúc xạ kế cầm tay/ kỹ thuật số","encategory":"Refractometer", "urlcategory": "khuc-xa-ke", "urlencategory": "refractometer"} ,
    {"category" :"Thiết bị thử nghiệm cơ, lý tính","encategory": "Mechanical and physical testing equipment", "urlcategory": "thiet-bi-thu-nghiem-co-ly-tinh", "urlencategory": "mechanical-and-physical-testing-equipment"},
    {"category" :"Lò nung","encategory":"Furnance", "urlcategory": "lo-nung", "urlencategory": "furnance"},
    {"category" :"Thiết bị ngành nhựa, cao su","encategory":"Rubber-Plastic Tester", "urlcategory": "thiet-bi-nganh-nhua-cao-su", "urlencategory": "rubber-plastic-tester"},
    {"category" :"Máy cất nước","encategory":"Water Distiller", "urlcategory": "may-cat-nuoc", "urlencategory": "water-distiller"},
    {"category" :"Camera/ Máy in","encategory":"Camera-Printer", "urlcategory": "camera-may-in", "urlencategory": "camera-printer"},
    {"category" :"Nồi hấp tiệt trùng","encategory":"Autoclave", "urlcategory": "noi-hap-tiet-trung", "urlencategory": "autoclave"},
    {"category" :"Máy ly tâm/ Máy lắc","encategory":"Centrifuge/Mixer", "urlcategory": "may-ly-tam-may-lac", "urlencategory": "centrifuge-mixer"},
    {"category" :"Hóa chất và thuốc thử","encategory":"Chemical", "urlcategory": "hoa-chat-va-thuoc-thu", "urlencategory": "chemical"},
    {"category" :"Phân cực kế/ Ống phân cực","encategory":"Polarimeter", "urlcategory": "phan-cuc-ke-ong-phan-cuc", "urlencategory": "polarimeter"},
    {"category" :"Thiết bị đo khí","encategory":"Gas measuring equipment", "urlcategory": "thiet-bi-do-khi", "urlencategory": "gas-measuring equipment"},
    {"category" :"Thiết bị đo tỷ trọng","encategory":"Density measuring equipment", "urlcategory": "thiet-bi-do-ty-trong", "urlencategory": "density-measuring-equipment"},
    {"category" :"Thiết bị đo độ nóng chảy", "encategory":"Melting measuring equipment", "urlcategory": "thiet-bi-do-do-nong-chay", "urlencategory": "melting-measuring-equipment"},
    {"category" :"So màu","encategory":"Color Comparing Equipment", "urlcategory": "so-mau", "urlencategory": "color-comparing-equipment"},
    {"category" :"Tủ an toàn sinh học/ Tủ hóa chất","encategory":"Safety Cabinet", "urlcategory": "tu-an-toan-sinh-hoc-hoa-chat", "urlencategory": "chemical-safety-cabinet"},
    {"category" :"Tủ sấy","encategory":"Drying Oven", "urlcategory": "tu-say", "urlencategory": "drying-oven"},
    {"category" :"Kính hiển vi","encategory":"Microscope", "urlcategory": "kinh-hien-vi", "urlencategory": "microscope"},
    {"category" :"Tủ ấm/ Tủ ấm lạnh","encategory":"Incubator", "urlcategory": "tu-am-lanh", "urlencategory": "incubator"},
    {"category" :"Máy đo độ nhớt","encategory":"Viscometer", "urlcategory": "may-do-do-nhot", "urlencategory": "viscometer"},
    {"category" :"Máy đo độ lưu biến","encategory":"Rheometer", "urlcategory": "may-do-do-luu-bien", "urlencategory": "rheometer"},
    {"category" :"Máy phân tích kết cấu","encategory":"Texture Analyzer", "urlcategory": "may-phan-tich-ket-cau", "urlencategory": "texture-analyzer"},
    {"category" : "Máy đo độ dẫn điện, EC", "encategory": "Conductivity meter, EC", "urlcategory": "may-do-do-dan-dien-ec", "urlencategory": "conductivity-meter-ec"},
    {"category" : "Máy đo độ pH", "encategory": "pH meter", "urlcategory": "may-do-do-ph", "urlencategory": "ph-meter"},
    {"category" : "Cân kỹ thuật", "encategory": "Technical scales", "urlcategory": "can-ky-thuat", "urlencategory": "technical-scales"},
    {"category" : "Cân phân tích", "encategory": "Analytical scales", "urlcategory": "can-phan-tich", "urlencategory": "analytical-scales"},
    {"category" : "Máy đo nhiệt lượng", "encategory": "Heat Meter", "urlcategory": "may-do-nhiet-luong", "urlencategory": "heat-meter"},
    {"category" : "Máy khuấy từ", "encategory": "Magnetic Stirrer", "urlcategory": "may-khuay-tu", "urlencategory": "magnetic-stirrer"},
    {"category" : "Máy khuấy đũa", "encategory": "Overhead Stirrer", "urlcategory": "may-khuay-dua", "urlencategory": "overhead-stirrer"},
    {"category" : "Máy đồng hóa", "encategory": "Homogenizer", "urlcategory": "may-dong-hoa", "urlencategory": "homogenizer"},
    {"category" : "Cô quay chân không", "encategory": "Rotary Evaporators", "urlcategory": "co-quay-chan-khong", "urlencategory": "rotary-evaporators"},
    {"category" : "Tủ vi khí hậu", "encategory": "Humidity chamber", "urlcategory": "tu-vi-khi-hau", "urlencategory": "humidity-chamber"},
    {"category" : "Quang phổ phân tử", "encategory": "Molecular Spectroscopy", "urlcategory": "quang-pho-phan-tu", "urlencategory": "molecular-spectroscopy"},
    {"category" : "Phân tích nguyên tố", "encategory": "Elemental analysis", "urlcategory": "phan-tich-nguyen-to", "urlencategory": "elemental-analysis"},
    {"category" : "Đặc tính bề mặt", "encategory": "Surface Characterization", "urlcategory": "dac-tinh-be-mat", "urlencategory": "surface-chacracterization"},
    {"category" : "Phân tích hạt", "encategory": "Particle Characterization", "urlcategory": "phan-tich-hat", "urlencategory": "particle-characterization"},
    {"category" : "Thiết bị môi trường", "encategory": "Environmental equipment", "urlcategory": "thiet-bi-moi-truong", "urlencategory": "environmental-equipment"},
    {"category" : "Thiết bị khoa học hình sự", "encategory": "Forensics Equipment", "urlcategory": "thiet-bi-khoa-hoc-hinh-su", "urlencategory": "forensics-equipment"}
];
 export default allcategories;